#!/bin/bash -e

doit ()
{
        echo starting diod
        $PATH_DIOD -l "localhost:2006" -x -m -e $PATH_EXPDIR &
        sleep 1
        echo mounting
        $PATH_DIODMOUNT -d -o uname=root,port=2006 -n localhost:$PATH_EXPDIR \
                        $PATH_MNTDIR

	echo creating file in regular file system
	dd status=noxfer if=/dev/zero of=$PATH_EXPDIR/a count=128 || fini 1

	echo comparing file in regular and diod file systems
	cmp $PATH_EXPDIR/a $PATH_MNTDIR/a || fini 1

        echo unmounting
        umount $PATH_MNTDIR
	rm -f $PATH_EXPDIR/a
        echo waiting for diod to terminate
        wait
}


TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root

doit >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
