#!/bin/bash -e

doit ()
{
	echo starting diod
	$PATH_DIOD -c $PATH_DIODCONF -f -l "localhost:2006" -x -m \
			-e $PATH_EXPDIR &
	sleep 1
	echo mounting with version=BOGUS
	if $PATH_DIODMOUNT -o uname=root,port=2006,version=BOGUS \
			-n localhost:$PATH_EXPDIR $PATH_MNTDIR; then
		echo mount successful
	else
		echo mount failed, retrying with version=9p2000.L
		$PATH_DIODMOUNT -o uname=root,port=2006,version=9P2000.L \
			-n localhost:$PATH_EXPDIR $PATH_MNTDIR
		echo mount successful
	fi
	echo unmounting
	umount $PATH_MNTDIR
	echo waiting for diod to terminate
	wait
}

TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root


doit >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
