#!/bin/bash -e

doit ()
{
	echo starting diod
	$PATH_DIOD -s $1 -l "localhost:2006" -x -m -e $PATH_EXPDIR &
	sleep 1
	echo mounting
	$PATH_DIODMOUNT -d -o uname=root,port=2006,version=9p2000.L \
			-n localhost:$PATH_EXPDIR $PATH_MNTDIR

	echo "creating files"
	mkdir $PATH_MNTDIR/b
	dd if=/dev/zero of=$PATH_MNTDIR/b/a count=1024 status=noxfer

	echo "comparing stat(2) results for file"
	./tstat $PATH_MNTDIR/b/a $PATH_EXPDIR/b/a
	echo "comparing stat(2) results for hard link"
	ln $PATH_EXPDIR/b/a $PATH_EXPDIR/b/c
	./tstat $PATH_MNTDIR/b/c $PATH_EXPDIR/b/c

	echo "comparing stat(2) results for directory"
	./tstat $PATH_MNTDIR/b $PATH_EXPDIR/b

	echo "removing files"
	rm -f $PATH_MNTDIR/b/a $PATH_MNTDIR/b/c
	rmdir $PATH_MNTDIR/b

	echo unmounting
	umount $PATH_MNTDIR
	echo waiting for diod to terminate
	wait
}

TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root

doit $TEST.stats >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
