starting diod
mounting
1024+0 records in
1024+0 records out
testing host file system
tflock: fd: blocking exclusive request succeeded
tflock: fd2: exclusive request failed: Resource temporarily unavailable
tflock: fd: shared request (downgrade) succeeded
tflock: fd2: shared request succeeded
tflock: fd2: exclusive request failed: Resource temporarily unavailable
tflock: fd: unlock succeeded
tflock: fd2: exclusive request succeeded
tflock: fd2: unlock succeeded
tflock: cleaning up
testing diod file system
diod: diod_flock: adding LOCK_NB to request
diod: flock LOCK_EX | LOCK_NB: Success
tflock: fd: blocking exclusive request succeeded
diod: flock LOCK_EX | LOCK_NB: Resource temporarily unavailable
tflock: fd2: exclusive request failed: Resource temporarily unavailable
diod: flock LOCK_SH | LOCK_NB: Success
tflock: fd: shared request (downgrade) succeeded
diod: flock LOCK_SH | LOCK_NB: Success
tflock: fd2: shared request succeeded
diod: flock LOCK_EX | LOCK_NB: Resource temporarily unavailable
tflock: fd2: exclusive request failed: Resource temporarily unavailable
diod: flock LOCK_UN: Success
tflock: fd: unlock succeeded
diod: flock LOCK_EX | LOCK_NB: Success
tflock: fd2: exclusive request succeeded
diod: flock LOCK_UN: Success
tflock: fd2: unlock succeeded
tflock: cleaning up
unmounting
waiting for diod to terminate
