starting diod
mounting
1024+0 records in
1024+0 records out
diod: flock 0x6: Success
tfcntl2: fd: blocking exclusive request succeeded
diod: flock 0x6: Permission denied
tfcntl2: fd2: exclusive request failed: Permission denied
diod: flock 0x5: No such file or directory
tfcntl2: fd: shared request (downgrade) succeeded
diod: flock 0x5: Success
tfcntl2: fd2: shared request succeeded
diod: flock 0x6: Permission denied
tfcntl2: fd2: exclusive request (upgrade) failed: Permission denied
diod: flock 0xc: Success
tfcntl2: fd: unlock succeeded
diod: flock 0x6: Success
tfcntl2: fd2: exclusive request succeeded
diod: flock 0xc: Success
tfcntl2: fd2: unlock succeeded
tfcntl2: cleaning up
unmounting
waiting for diod to terminate
