starting diod
mounting
1024+0 records in
1024+0 records out
testing host file system
tfcntl2: fd: blocking exclusive request succeeded
tfcntl2: fd2: exclusive request succeeded
tfcntl2: fd2(child): exclusive request failed: Resource temporarily unavailable
tfcntl2: child exited normally
tfcntl2: fd: unlock succeeded
tfcntl2: fd2(child): exclusive request succeeded
tfcntl2: child exited normally
tfcntl2: fd2: exclusive request succeeded
tfcntl2: fd2: unlock succeeded
tfcntl2: cleaning up
testing diod file system
diod: diod_lock: converting SETLKW to SETLK
diod: flock LOCK_EX | LOCK_NB: Success
tfcntl2: fd: blocking exclusive request succeeded
diod: flock LOCK_EX | LOCK_NB: Resource temporarily unavailable
tfcntl2: fd2: exclusive request failed, this is incorrect behavior!: Resource temporarily unavailable
diod: flock LOCK_EX | LOCK_NB: Resource temporarily unavailable
tfcntl2: fd2(child): exclusive request failed: Resource temporarily unavailable
tfcntl2: child exited normally
diod: flock LOCK_UN: Success
tfcntl2: fd: unlock succeeded
diod: flock LOCK_EX | LOCK_NB: Success
tfcntl2: fd2(child): exclusive request succeeded
tfcntl2: child exited normally
diod: flock LOCK_EX | LOCK_NB: Success
tfcntl2: fd2: exclusive request succeeded
diod: flock LOCK_UN: Success
tfcntl2: fd2: unlock succeeded
tfcntl2: cleaning up
unmounting
waiting for diod to terminate
