#!/bin/bash -e

doit ()
{
        echo starting diod with max 1mb atomic transfers
        $PATH_DIOD -A 1 -l "localhost:2006" -x -m -e $PATH_EXPDIR &
        sleep 1
        echo mounting
        $PATH_DIODMOUNT -d -o uname=root,port=2006 -n localhost:$PATH_EXPDIR \
                        $PATH_MNTDIR

	echo creating file in regular file system
	dd status=noxfer bs=1048576 if=/dev/zero of=$PATH_EXPDIR/a count=4

	echo reading file with 1mb transfers
	dd status=noxfer bs=1048576 of=/dev/null if=$PATH_EXPDIR/a
	echo reading file with 2mb transfers
	dd status=noxfer bs=2097152 of=/dev/null if=$PATH_EXPDIR/a
	echo reading file with odd size transfers
	dd status=noxfer bs=131075 of=/dev/null if=$PATH_EXPDIR/a

        echo unmounting
        umount $PATH_MNTDIR
	rm -f $PATH_EXPDIR/a
        echo waiting for diod to terminate
        wait
}


TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root

doit >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
