starting diod with max 1mb atomic transfers
mounting
writing file with 1mb transfers and verifying
diod: awrite: rsize 65503 count 1048576 offset 0
diod: awrite:  allocated 1048576 byte cache
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 983073 offset 65503
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 917570 offset 131006
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 852067 offset 196509
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 786564 offset 262012
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 721061 offset 327515
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 655558 offset 393018
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 590055 offset 458521
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 524552 offset 524024
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 459049 offset 589527
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 393546 offset 655030
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 328043 offset 720533
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 262540 offset 786036
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 197037 offset 851539
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 131534 offset 917042
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 66031 offset 982545
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 528 count 528 offset 1048048
diod: awrite:   cached 528 bytes
diod: awrite:   wrote 1048576 bytes at offset 0
diod: awrite:   freed 1048576 byte cache
diod: awrite: rsize 65503 count 1048576 offset 1048576
diod: awrite:  allocated 1048576 byte cache
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 983073 offset 1114079
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 917570 offset 1179582
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 852067 offset 1245085
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 786564 offset 1310588
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 721061 offset 1376091
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 655558 offset 1441594
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 590055 offset 1507097
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 524552 offset 1572600
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 459049 offset 1638103
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 393546 offset 1703606
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 328043 offset 1769109
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 262540 offset 1834612
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 197037 offset 1900115
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 131534 offset 1965618
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 66031 offset 2031121
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 528 count 528 offset 2096624
diod: awrite:   cached 528 bytes
diod: awrite:   wrote 1048576 bytes at offset 1048576
diod: awrite:   freed 1048576 byte cache
diod: awrite: rsize 65503 count 1048576 offset 2097152
diod: awrite:  allocated 1048576 byte cache
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 983073 offset 2162655
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 917570 offset 2228158
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 852067 offset 2293661
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 786564 offset 2359164
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 721061 offset 2424667
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 655558 offset 2490170
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 590055 offset 2555673
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 524552 offset 2621176
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 459049 offset 2686679
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 393546 offset 2752182
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 328043 offset 2817685
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 262540 offset 2883188
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 197037 offset 2948691
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 131534 offset 3014194
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 66031 offset 3079697
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 528 count 528 offset 3145200
diod: awrite:   cached 528 bytes
diod: awrite:   wrote 1048576 bytes at offset 2097152
diod: awrite:   freed 1048576 byte cache
diod: awrite: rsize 65503 count 1048576 offset 3145728
diod: awrite:  allocated 1048576 byte cache
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 983073 offset 3211231
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 917570 offset 3276734
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 852067 offset 3342237
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 786564 offset 3407740
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 721061 offset 3473243
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 655558 offset 3538746
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 590055 offset 3604249
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 524552 offset 3669752
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 459049 offset 3735255
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 393546 offset 3800758
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 328043 offset 3866261
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 262540 offset 3931764
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 197037 offset 3997267
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 131534 offset 4062770
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 65503 count 66031 offset 4128273
diod: awrite:   cached 65503 bytes
diod: awrite: rsize 528 count 528 offset 4193776
diod: awrite:   cached 528 bytes
diod: awrite:   wrote 1048576 bytes at offset 3145728
diod: awrite:   freed 1048576 byte cache
4+0 records in
4+0 records out
diod: aread: rsize 65503 count 2097152 offset 0
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 0
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 2031649 offset 65503
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1966146 offset 131006
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1900643 offset 196509
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1835140 offset 262012
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1769637 offset 327515
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1704134 offset 393018
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1638631 offset 458521
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1573128 offset 524024
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1507625 offset 589527
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1442122 offset 655030
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1376619 offset 720533
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1311116 offset 786036
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1245613 offset 851539
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1180110 offset 917042
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1114607 offset 982545
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1049104 offset 1048048
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 1048576
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 1048576
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 1114079
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 1179582
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 1245085
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 1310588
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 1376091
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 1441594
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 1507097
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 1572600
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 1638103
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 1703606
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 1769109
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 1834612
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 1900115
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 1965618
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 2031121
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 2096624
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 2097152 offset 2097152
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 2097152
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 2031649 offset 2162655
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1966146 offset 2228158
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1900643 offset 2293661
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1835140 offset 2359164
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1769637 offset 2424667
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1704134 offset 2490170
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1638631 offset 2555673
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1573128 offset 2621176
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1507625 offset 2686679
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1442122 offset 2752182
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1376619 offset 2817685
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1311116 offset 2883188
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1245613 offset 2948691
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1180110 offset 3014194
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1114607 offset 3079697
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 1049104 offset 3145200
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 3145728
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 3145728
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 3211231
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 3276734
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 3342237
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 3407740
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 3473243
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 3538746
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 3604249
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 3669752
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 3735255
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 3800758
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 3866261
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 3931764
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 3997267
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 4062770
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 4128273
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 4193776
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 2097152 offset 4194304
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 4194304
diod: aread:   read 0 bytes from cache
diod: aread:   freed 0 byte cache
size is 4194304
unmounting
waiting for diod to terminate
