#!/bin/bash -e

# Note: I added this test because it freaked me out to see an append
# pwrite at offset 0.  However as the hexdump shows, this must be correct
# because we get the desired result.

doit ()
{
        echo starting diod
        $PATH_DIOD -d 0x04 -l "localhost:2006" -x -m -e $PATH_EXPDIR &
        sleep 1
        echo mounting
        $PATH_DIODMOUNT -d -o uname=root,port=2006 -n localhost:$PATH_EXPDIR \
                        $PATH_MNTDIR

	echo writing 4k file
	dd status=noxfer bs=4096 if=/dev/zero of=$PATH_MNTDIR/a count=1
	echo appending 3 bytes
	echo -n foo >>$PATH_MNTDIR/a
	echo verifying
	cmp $PATH_EXPDIR/a $PATH_MNTDIR/a
	echo "size is `stat -c "%s" $PATH_EXPDIR/a`"
	hexdump -C $PATH_EXPDIR/a

        echo unmounting
        umount $PATH_MNTDIR
	rm -f $PATH_EXPDIR/a $PATH_EXPDIR/b
        echo waiting for diod to terminate
        wait
}


TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root

doit >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
