#!/bin/bash -e

doit ()
{
	echo starting diod
	$PATH_DIOD -s $1 -d 0x08 -l "127.0.0.1:2006" -x -e $PATH_EXPDIR &
	sleep 1
	echo mounting
	$PATH_DIODMOUNT -d -o uname=root,port=2006 \
			-n 127.0.0.1:$PATH_EXPDIR $PATH_MNTDIR

	echo creating setgid directory
	mkdir $PATH_EXPDIR/dir
	chgrp 42 $PATH_EXPDIR/dir
	chmod g+s $PATH_EXPDIR/dir
	echo testing host file system create with effective gid
	./tfsgid 42 $PATH_EXPDIR/a || :
	echo testing host file system create with setgid parent
	./tfsgid 44 $PATH_EXPDIR/dir/a

	echo testing diod file system create with effective gid
	./tfsgid 42 $PATH_MNTDIR/a || :
	echo testing diod file system create with setgid parent
	./tfsgid 44 $PATH_EXPDIR/dir/a

	rm -rf $PATH_MNTDIR/dir
	echo unmounting
	umount $PATH_MNTDIR
	echo waiting for diod to terminate
	wait
}

TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root

doit $TEST.stats >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
