queue_rules:
  - name: default
    batch_size: 1
    queue_conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - -title~=^\[*[Ww][Ii][Pp]
      - "approved-reviews-by=@chaos/diod-admins"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
    merge_conditions:
      - base=master
      - label="merge-when-passing"
      - label!="work-in-progress"
      - "approved-reviews-by=@chaos/diod-admins"
      - "#approved-reviews-by>0"
      - "#changes-requested-reviews-by=0"
      - -title~=^\[*[Ww][Ii][Pp]
    update_method: rebase
    merge_method: merge

merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: rebase and merge when passing all checks
    conditions: []
    actions:
      queue:
