#!/bin/bash -e

TEST=$(basename $0 | cut -d- -f1)
# test $(id -u) == 0 || exit 77 #skip if not root
${MISC_BUILDDIR}/tlua || exit 77 #skip if no lua
${MISC_BUILDDIR}/tconf -c ${MISC_SRCDIR}/$TEST.conf -e >$TEST.out 2>&1
diff ${MISC_SRCDIR}/$TEST.exp $TEST.out >$TEST.diff
