tnpsrv: P9_TVERSION tag 65535 msize 8192 version '9P2000.L'
tnpsrv: P9_RVERSION tag 65535 msize 8192 version '9P2000.L'
tnpsrv: P9_TAUTH tag 0 afid 0 uname '' aname '/foo' n_uname 0
tnpsrv: P9_RLERROR tag 0 ecode 0
tnpsrv: P9_TATTACH tag 1 fid 0 afid -1 uname '' aname '/foo' n_uname 0
tnpsrv: user lookup: 0
tnpsrv: P9_RATTACH tag 1 qid (0000000000000003 2 '')
tnpsrv: P9_TATTACH tag 2 fid 1 afid -1 uname '' aname '/foo' n_uname 0
tnpsrv: P9_RATTACH tag 2 qid (0000000000000003 2 '')
tnpsrv: P9_TATTACH tag 3 fid 2 afid -1 uname '' aname '/foo' n_uname 1
tnpsrv: user lookup: 1
tnpsrv: P9_RATTACH tag 3 qid (0000000000000003 2 '')
tnpsrv: P9_TATTACH tag 4 fid 3 afid -1 uname '' aname '/foo' n_uname 1
tnpsrv: P9_RATTACH tag 4 qid (0000000000000003 2 '')
tnpsrv: P9_TATTACH tag 5 fid 4 afid -1 uname '' aname '/foo' n_uname 0
tnpsrv: P9_RATTACH tag 5 qid (0000000000000003 2 '')
tnpsrv: P9_TCLUNK tag 6 fid 4
tnpsrv: P9_RCLUNK tag 6
tnpsrv: P9_TCLUNK tag 7 fid 3
tnpsrv: P9_RCLUNK tag 7
tnpsrv: P9_TCLUNK tag 8 fid 2
tnpsrv: P9_RCLUNK tag 8
tnpsrv: P9_TCLUNK tag 9 fid 1
tnpsrv: P9_RCLUNK tag 9
tnpsrv: P9_TCLUNK tag 10 fid 0
tnpsrv: P9_RCLUNK tag 10
