tnpsrv2: attached
tnpsrv2: created file
tnpsrv2: write 409600 bytes
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: walk
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: open
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: read 409600 bytes
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: unlink
tnpsrv2: mkdir
tnpsrv2: created /foo/0
tnpsrv2: created /foo/1
tnpsrv2: created /foo/2
tnpsrv2: created /foo/3
tnpsrv2: created /foo/4
tnpsrv2: created /foo/5
tnpsrv2: created /foo/6
tnpsrv2: created /foo/7
tnpsrv2: created /foo/8
tnpsrv2: created /foo/9
tnpsrv2: created /foo/10
tnpsrv2: created /foo/11
tnpsrv2: created /foo/12
tnpsrv2: created /foo/13
tnpsrv2: created /foo/14
tnpsrv2: created /foo/15
tnpsrv2: created /foo/16
tnpsrv2: created /foo/17
tnpsrv2: created /foo/18
tnpsrv2: created /foo/19
tnpsrv2: created /foo/20
tnpsrv2: created /foo/21
tnpsrv2: created /foo/22
tnpsrv2: created /foo/23
tnpsrv2: created /foo/24
tnpsrv2: created /foo/25
tnpsrv2: created /foo/26
tnpsrv2: created /foo/27
tnpsrv2: created /foo/28
tnpsrv2: created /foo/29
tnpsrv2: created /foo/30
tnpsrv2: created /foo/31
tnpsrv2: created /foo/32
tnpsrv2: created /foo/33
tnpsrv2: created /foo/34
tnpsrv2: created /foo/35
tnpsrv2: created /foo/36
tnpsrv2: created /foo/37
tnpsrv2: created /foo/38
tnpsrv2: created /foo/39
tnpsrv2: created /foo/40
tnpsrv2: created /foo/41
tnpsrv2: created /foo/42
tnpsrv2: created /foo/43
tnpsrv2: created /foo/44
tnpsrv2: created /foo/45
tnpsrv2: created /foo/46
tnpsrv2: created /foo/47
tnpsrv2: created /foo/48
tnpsrv2: created /foo/49
tnpsrv2: created /foo/50
tnpsrv2: created /foo/51
tnpsrv2: created /foo/52
tnpsrv2: created /foo/53
tnpsrv2: created /foo/54
tnpsrv2: created /foo/55
tnpsrv2: created /foo/56
tnpsrv2: created /foo/57
tnpsrv2: created /foo/58
tnpsrv2: created /foo/59
tnpsrv2: created /foo/60
tnpsrv2: created /foo/61
tnpsrv2: created /foo/62
tnpsrv2: created /foo/63
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: clunk
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: unlink
tnpsrv2: rmdir
