#!/bin/bash -e

bg_test ()
{
  local sockfile=$1
  while ! test -S $sockfile; do
    sleep 0.1
  done
  ${TOP_BUILDDIR}/src/cmd/diodload -r 2 -s $sockfile 2>/dev/null
}

TEST=$(basename $0 | cut -d- -f1)
sockfile=$(mktemp)
bg_test $sockfile &
${MISC_SRCDIR}/memcheck ${TOP_BUILDDIR}/src/cmd/diod -L $TEST.diod -c /dev/null -n -e ctl -l $sockfile -s >$TEST.out 2>&1
rm -f $sockfile
wait %1
