#!/bin/bash

PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
if [ $# -ne 1 ]; then
    echo "Usage runtest test" 2>&1
    exit 1
fi
TEST=$1

if [ -z "$PATH_DIOD" ]; then
    echo "PATH_DIOD is not set" 2>&1
    exit 1
fi

rm -f $TEST.diod $TEST.out
ulimit -c unlimited

umask 022
PATH_EXPDIR=$(mktemp -d) || exit 1
export PATH_EXPDIR

./conjoin \
    "$PATH_DIOD -s -c /dev/null -n -d 1 -L $TEST.diod -e $PATH_EXPDIR" \
    "$TEST $PATH_EXPDIR" \
    >$TEST.out 2>&1
rc=$?
if [ $rc != 0 ]; then
    echo "test exited with $rc" >>$TEST.out
    exit $rc
fi

[ -d "$PATH_EXPDIR" ] && rm -rf $PATH_EXPDIR

diff $TEST.exp $TEST.out >$TEST.diff
exit $?
