#!/bin/bash

PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
if [ $# -ne 1 ]; then
    echo "Usage runtest test" 2>&1
    exit 1
fi
TEST=$1
rm -f $TEST.out $TEST.diod

if [ -z "$PATH_DIOD" ]; then
    echo "PATH_DIOD is not set" 2>&1
    exit 1
fi

# Special case for t11 which requires root
if [ "`basename $TEST`" = "t11" ] && [ $(id -u) != 0 ]; then
    echo "t11 requires root" >$TEST.out
    exit 77
fi
# Special case for t11 which requires non-root
if [ "`basename $TEST`" = "t12" ] && [ $(id -u) == 0 ]; then
    echo "t12 requires non-root" >$TEST.out
    exit 77
fi

rm -f $TEST.diod $TEST.out
ulimit -c unlimited

umask 022
PATH_EXPDIR=$(mktemp -d) || exit 1
export PATH_EXPDIR

export MALLOC_CHECK_=3

./conjoin \
    "$PATH_DIOD -s -c /dev/null -n -d 1 -L $TEST.diod -e $PATH_EXPDIR" \
    "$TEST $PATH_EXPDIR" \
    >$TEST.out 2>&1
rc=$?
if [ $rc != 0 ]; then
    echo "test exited with $rc" >>$TEST.out
    exit $rc
fi

[ -d "$PATH_EXPDIR" ] && rm -rf $PATH_EXPDIR

diff $TEST.exp $TEST.out >$TEST.diff
exit $?
