#!/bin/bash -e

echo creating testfile
cp $PATH_DIOD $PATH_EXPDIR/testfile
tmpfile=`mktemp`
echo reading testfile
./tread "$@" $tmpfile testfile
echo comparing result
if ! cmp $tmpfile $PATH_EXPDIR/testfile; then
    echo results differ
    exit 1
fi
rm -f $tmpfile
exit 0
