#!/bin/bash -e

echo creating file with three xattrs set
touch $PATH_EXPDIR/testfile
./tsetxattr "$@" testfile user.foo fooval 
./tsetxattr "$@" testfile user.bar barval 
./tsetxattr "$@" testfile user.baz bazval 
./tgetxattr "$@" testfile user.foo user.bar user.baz
./tremovexattr "$@" testfile user.foo
./tremovexattr "$@" testfile user.bar
./tremovexattr "$@" testfile user.baz
./tgetxattr "$@" testfile
exit 0
