#!/bin/bash -e

./testopenfid "$@" open_walk 
./testopenfid "$@" open_remove_read
./testopenfid "$@" open_remove_getattr
./testopenfid "$@" open_remove_setattr
./testopenfid "$@" open_remove_create_setattr
