#!/bin/bash

PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
if [ $# -ne 1 ]; then
    echo "Usage runtest test" 2>&1
    exit 1
fi
TEST=$1
rm -f $TEST.out $TEST.diod

if [ -z "$PATH_DIODMOUNT" ]; then
    echo "PATH_DIODMOUNT is not set" 2>&1
    exit 1
fi
if [ -z "$PATH_DIOD" ]; then
    echo "PATH_DIOD is not set" 2>&1
    exit 1
fi

if test $(id -u) != 0; then
    echo "not root - skipping" >$TEST.out
    exit 77
fi
if ! modprobe 9p 2>/dev/null; then
    echo "9p not loaded - skipping" >$TEST.out
    exit 77
fi
rm -f $TEST.diod $TEST.out
# Special case for t29 which requires tclsh
if [ "`basename $TEST`" = "t29" ] && ! which tclsh >/dev/null 2>&1; then
    echo "tclsh is not installed" >$TEST.out
    exit 77
fi
# Special diod option for t30 (tests --allsquash)
if [ "`basename $TEST`" = "t30" ]; then
    opt="-S" 
fi

ulimit -c unlimited

umask 022
PATH_MNTDIR=$(mktemp -d) || exit 1
PATH_EXPDIR=$(mktemp -d) || exit 1
chmod 755 $PATH_MNTDIR $PATH_EXPDIR
export PATH_EXPDIR
export PATH_MNTDIR

export MALLOC_CHECK_=3

./kconjoin \
    "$PATH_DIOD $opt -s -c /dev/null -n -d 1 -L $TEST.diod -e $PATH_EXPDIR" \
    "$PATH_DIODMOUNT -n -owfdno=0,rfdno=0 nohost:$PATH_EXPDIR $PATH_MNTDIR" \
    "$TEST" \
    >$TEST.out 2>&1
rc=$?
if [ $rc != 0 ]; then
    echo "test exited with $rc" >>$TEST.out
    exit $rc
fi

[ -d "$PATH_EXPDIR" ] && rm -rf $PATH_EXPDIR
[ -d "$PATH_MNTDIR" ] && rm -rf $PATH_MNTDIR

diff $TEST.exp $TEST.out >$TEST.diff
exit $?
