#!/bin/bash -e

echo writing 4k file
dd status=noxfer bs=4096 if=/dev/zero >>$PATH_MNTDIR/a count=1
echo appending 3 bytes
echo -n foo >>$PATH_MNTDIR/a
echo verifying
cmp $PATH_EXPDIR/a $PATH_MNTDIR/a
echo "size is `stat -c "%s" $PATH_EXPDIR/a`"
hexdump -C $PATH_EXPDIR/a
