kconjoin: diodmount exited with rc=0
1024+0 records in
1024+0 records out
testing host file system
fd: open
fd: write-locked
fd2: open
second flock failed as it should - PASS: Resource temporarily unavailable
testing diod file system
fd: open
fd: write-locked
fd2: open
second flock failed as it should - PASS: Resource temporarily unavailable
kconjoin: t24 exited with rc=0
kconjoin: diod exited with rc=0
