#!/bin/bash -e

PATH_POSTMARK=$(pwd)/postmark/postmark
(pushd $PATH_MNTDIR >/dev/null
$PATH_POSTMARK <<EOT
set size 10 100000
set number 2000
set transactions 2000
show
run
quit
EOT
popd $PATH_MNTDIR >/dev/null
) >t33.postmark
