#!/bin/bash

echo creating 100mb file
dd if=/dev/zero of=$PATH_MNTDIR/file bs=1024k count=100 status=noxfer
echo scrubbing
scrub -s 100m $PATH_MNTDIR/file >/dev/null &
echo interrupting
sleep 0.5
kill -15 %1
wait %1 >/dev/null 2>&1

exit 0
