#!/bin/bash 

# Watch for "WARNING: at fs/inode.c:280 drop_nlink+0x43/0x50()"
# See post to v9fs-developer Oct 24, 2012 by Mario Titas
#
# Drop the dmesg check since it was racy and it's 12 years since
# that bug was identified. Keep the file system workload since
# presumably it tickled something back then.

cd $PATH_MNTDIR || exit 1
echo creating dirs
mkdir -p {1,2,3,4}/{1,2,3,4}/{1,2,3,4}/{1,2,3,4}
echo removing dirs
rm -rf {1,2,3,4}

exit 0
