kconjoin: diodmount exited with rc=0
# file: testfile
# owner: root
# group: root
user::rw-
user:root:r--
group::r--
mask::r--
other::r--

# file: testfile
# owner: root
# group: root
user::rw-
group::r--
mask::r--
other::r--

# file: testdir
# owner: root
# group: root
user::rwx
group::r-x
other::r-x
default:user::rwx
default:user:root:r--
default:group::r-x
default:mask::r-x
default:other::r-x

kconjoin: t43 exited with rc=0
kconjoin: diod exited with rc=0
