#!/bin/bash

PATH=/sbin:/usr/sbin:/bin:/usr/bin:$PATH
if [ $# -ne 1 ]; then
    echo "Usage runtest test" 2>&1
    exit 1
fi
TEST=$1

if [ -z "$PATH_EXPDIR" ]; then
    echo "PATH_EXPDIR is not set" 2>&1
    exit 1
fi
if [ -z "$PATH_MNTDIR" ]; then
    echo "PATH_MNTDIR is not set" 2>&1
    exit 1
fi
if [ -z "$PATH_DIODMOUNT" ]; then
    echo "PATH_DIODMOUNT is not set" 2>&1
    exit 1
fi
if [ -z "$PATH_DIOD" ]; then
    echo "PATH_DIOD is not set" 2>&1
    exit 1
fi

if test $(id -u) != 0; then
    echo "not root - skipping" >$TEST.out
    exit 77
fi
if ! modprobe 9p; then
    echo "9p not loaded - skipping" >$TEST.out
    exit 77
fi
if ! test -d $PATH_EXPDIR; then
    echo "test directory vanished" >$TEST.out
    exit 77
fi
rm -rf $PATH_EXPDIR/*
rm -f $TEST.diod $TEST.out
ulimit -c unlimited

if ! [ -x /usr/bin/munge ] || ! /usr/bin/munge -n >/dev/null 2>&1; then
    AUTHARG="-n"
fi

./kconjoin \
    "$PATH_DIOD $AUTHARG -d 1 -L $TEST.diod -e $PATH_EXPDIR -s $TEST.stats" \
    "$PATH_DIODMOUNT -S nohost:$PATH_EXPDIR $PATH_MNTDIR" \
    "$TEST" \
    >$TEST.out 2>&1
rc=$?
if [ $rc != 0 ]; then
    echo "test exited with $rc" >>$TEST.out
    exit $rc
fi

diff $TEST.exp $TEST.out >$TEST.diff
exit $?
