#!/bin/bash -e

echo creating file in regular file system
dd status=noxfer if=/dev/zero of=$PATH_EXPDIR/a count=128

echo comparing file in regular and diod file systems
cmp $PATH_EXPDIR/a $PATH_MNTDIR/a
