#!/bin/bash -e

doit ()
{
	echo starting diod
	$PATH_DIOD -s $1 -l "127.0.0.1:2006" -x -e $PATH_EXPDIR &
	sleep 1
	echo mounting
	$PATH_DIODMOUNT -d2006 -ouname=root \
			-n 127.0.0.1:$PATH_EXPDIR $PATH_MNTDIR

	echo trying rename
	touch $PATH_MNTDIR/a
	./trename $PATH_MNTDIR/a $PATH_MNTDIR/b

	echo trying rename to new directory
	mkdir -p $PATH_MNTDIR/dir
	./trename $PATH_MNTDIR/b $PATH_MNTDIR/dir/c
	rm -f $PATH_MNTDIR/dir/c
	rmdir $PATH_MNTDIR/dir

	echo unmounting
	umount $PATH_MNTDIR
	echo waiting for diod to terminate
	wait
}

TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root
modprobe 9p || exit 77 #skip if no 9p

doit $TEST.stats >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
