#!/bin/bash -e

doit ()
{
	echo starting diod
	$PATH_DIOD -s $1 -l "127.0.0.1:2006" -x -e $PATH_EXPDIR &
	sleep 1
	echo mounting
	$PATH_DIODMOUNT -d2006 -o uname=root \
			-n 127.0.0.1:$PATH_EXPDIR $PATH_MNTDIR

	echo running statfs comparison
	./tstatfs $PATH_EXPDIR $PATH_MNTDIR

	echo unmounting
	umount $PATH_MNTDIR
	echo waiting for diod to terminate
	wait
}

TEST=$(basename $0 | cut -d- -f1)
test $(id -u) == 0 || exit 77 #skip if not root
modprobe 9p || exit 77 #skip if no 9p

doit $TEST.stats >$TEST.out 2>&1

diff $TEST.exp $TEST.out >$TEST.diff
