#!/bin/bash -e

rc=0

echo "creating objects"
mkdir $PATH_MNTDIR/b
dd if=/dev/zero of=$PATH_MNTDIR/b/a count=1024 status=noxfer
ln $PATH_EXPDIR/b/a $PATH_EXPDIR/b/c

echo "comparing stat(2) results for file"
./tstat $PATH_MNTDIR/b/a $PATH_EXPDIR/b/a || rc=1

echo "comparing stat(2) results for hard link"
./tstat $PATH_MNTDIR/b/c $PATH_EXPDIR/b/c || rc=1

echo "comparing stat(2) results for directory"
./tstat $PATH_MNTDIR/b $PATH_EXPDIR/b || rc=1

exit $rc
