#!/bin/bash -e

testmode ()
{
	for i in 0 1 2 3 4 5 6 7; do
		chmod $i$i$i$i $1
		stat -c "%a" $2
	done
}

echo "creating file and directory"
touch $PATH_MNTDIR/a
mkdir $PATH_MNTDIR/b

echo "testing file server to client"
testmode $PATH_EXPDIR/a $PATH_MNTDIR/a
echo "testing file client to server"
testmode $PATH_MNTDIR/a $PATH_EXPDIR/a
echo "testing directory server to client"
testmode $PATH_EXPDIR/b $PATH_MNTDIR/b
echo "testing directory client to server"
testmode $PATH_MNTDIR/b $PATH_EXPDIR/b
