starting diod with max 1mb atomic transfers
mounting
creating file in regular file system
4+0 records in
4+0 records out
reading file with 1mb transfers
diod: aread: rsize 65503 count 1048576 offset 0
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 0
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 65503
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 131006
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 196509
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 262012
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 327515
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 393018
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 458521
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 524024
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 589527
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 655030
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 720533
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 786036
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 851539
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 917042
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 982545
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 1048048
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 1048576
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 1048576
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 1114079
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 1179582
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 1245085
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 1310588
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 1376091
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 1441594
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 1507097
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 1572600
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 1638103
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 1703606
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 1769109
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 1834612
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 1900115
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 1965618
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 2031121
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 2096624
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 2097152
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 2097152
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 2162655
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 2228158
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 2293661
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 2359164
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 2424667
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 2490170
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 2555673
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 2621176
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 2686679
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 2752182
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 2817685
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 2883188
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 2948691
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 3014194
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 3079697
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 3145200
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 3145728
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 1048576 bytes at offset 3145728
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 983073 offset 3211231
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 917570 offset 3276734
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 852067 offset 3342237
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 786564 offset 3407740
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 721061 offset 3473243
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 655558 offset 3538746
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 590055 offset 3604249
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 524552 offset 3669752
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 459049 offset 3735255
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 393546 offset 3800758
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 328043 offset 3866261
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 262540 offset 3931764
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 197037 offset 3997267
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 131534 offset 4062770
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 65503 count 66031 offset 4128273
diod: aread:   read 65503 bytes from cache
diod: aread: rsize 528 count 528 offset 4193776
diod: aread:   read 528 bytes from cache
diod: aread:   freed 1048576 byte cache
diod: aread: rsize 65503 count 1048576 offset 4194304
diod: aread:  allocated 1048576 byte cache
diod: aread:   read 0 bytes at offset 4194304
diod: aread:   read 0 bytes from cache
diod: aread:   freed 0 byte cache
4+0 records in
4+0 records out
unmounting
waiting for diod to terminate
