#!/bin/bash -e

echo creating setgid directory
mkdir $PATH_EXPDIR/dir
chgrp 42 $PATH_EXPDIR/dir
chmod g+s $PATH_EXPDIR/dir
echo testing host file system create with effective gid
./tfsgid 42 $PATH_EXPDIR/a || :
echo testing host file system create with setgid parent
./tfsgid 44 $PATH_EXPDIR/dir/a

echo testing diod file system create with effective gid
./tfsgid 42 $PATH_MNTDIR/a || :
echo testing diod file system create with setgid parent
./tfsgid 44 $PATH_EXPDIR/dir/a
