kconjoin: diodmount exited with rc=0
creating setgid directory
testing host file system create with effective gid
tfsgid: file gid is same as egid and different than gid
testing host file system create with setgid parent
tfsgid: file gid is different than egid and different than gid
testing diod file system create with effective gid
tfsgid: file gid is same as egid and different than gid
testing diod file system create with setgid parent
tfsgid: file gid is different than egid and different than gid
kconjoin: t25 exited with rc=0
kconjoin: diod exited with rc=0
