#!/bin/bash -e

echo creating file with user:group 0:0
touch $PATH_EXPDIR/a
chown 0:0 $PATH_EXPDIR/a

echo chgrp to gid 42
echo before: `stat --printf "%g\n" $PATH_MNTDIR/a`
chgrp 42 $PATH_MNTDIR/a
echo after: `stat --printf "%g\n" $PATH_MNTDIR/a`
