#!/bin/bash -e

echo creating testfile
cp $PATH_DIOD $PATH_EXPDIR/testfile
tmpfile=`mktemp`
echo reading testfile
./tread "$@" testfile $tmpfile
echo comparing result
if ! cmp $PATH_EXPDIR/testfile $tmpfile; then
    echo results differ
    exit 1
fi
rm -f $tmpfile
exit 0
